name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Test:
    strategy:
      matrix:
        go-version: [1.14.x, 1.15.x]
        platform: [ubuntu-latest]

    runs-on: ${{ matrix.platform }}

    services:
      arangodb:
        image: arangodb
        ports:
        - 8529:8529
        env:
          ARANGO_NO_AUTH: 1
        options: >-
          --health-cmd "wget localhost:8529/_api/version -O - >/dev/null 2>&1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Install Go
        if: success()
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Run Tests
        run: go test -v ./...
        env:
          ARANGODB_HOST: localhost
          ARANGODB_PORT: ${{ job.services.arangodb.ports[8529] }}


